version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/FLASK_APP
    depends_on:
      - database
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=env
  database:
    image: postgres:13
    ports:
      - 5432:5432 
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=flask_main.dev